set_background(1, 0)
#choice(1, 0, 'text1', 'text2')
#choice_to_id(2, 0, 3, 0)
#dialog(2, 'name', 'text')
#set_character(3, 1, 0)
#play_music(4, "ambient1")
#clear_character(5)
#play_sound(5, "slash")
#set_id(5, 6)
